TASKS = [
    "scene_classification",
    "environment_state",
    "object_detection",
    "semantic_segmentation",
    "instance_segmentation",
    "ocr",
    "event_qa",
    "restoration_pairing",
    "urban_structure",
]

TASK_NAMES = {
    "scene_classification": "场景识别",
    "environment_state": "环境状态识别",
    "object_detection": "目标检测/计数",
    "semantic_segmentation": "语义分割",
    "instance_segmentation": "实例分割",
    "ocr": "OCR",
    "event_qa": "事件理解/QA",
    "restoration_pairing": "图像复原配对",
    "urban_structure": "城市结构理解",
}

SCENE_LABELS = [
    "commercial_district",
    "construction_site",
    "farmland",
    "industrial_area",
    "mixed",
    "natural_vegetation",
    "residential_area",
    "river",
    "school",
    "thoroughfare",
    "工地",
    "工业园区",
    "交通要道",
    "居住区",
    "商业区",
    "农林园田",
    "学校区",
]

URBAN_STRUCTURE_LABELS = [
    "commercial_service_area",
    "construction_site",
    "cultivated_land",
    "educational_facility",
    "healthcare_facility",
    "industrial_park",
    "natural_idle_land",
    "parking_facility",
    "residential_area",
    "sports_activity_ground",
    "urban_road_infrastructure",
    "water_bodies_hydraulic_infrastructure",
    "铁路",
    "湿地公园",
    "公墓",
    "市场",
    "菜市场",
    "加油站",
    "通信/电力塔",
    "酒店",
    "学校",
    "医院",
    "林地",
    "农田",
    "湖面",
    "湿地",
]

OBJECT_LABELS = [
    "boat",
    "car",
    "distribution_facility",
    "distribution_dominance",
    "excavator",
    "fireworks",
    "garbage",
    "non_motor_vehicle",
    "pedestrian",
    "residential_building",
    "sports_court",
    "tower_crane",
    "vendor",
    "ship",
    "vehicle",
    "person",
    "crane",
    "truck",
    "building",
    "tower",
    "smoke",
    "fire",
    "illegal_parking",
]

SEGMENT_LABELS = ["道路", "河道", "农林园田", "湿地公园", "建筑物", "水体"]

EVENT_LABELS = [
    "不受控燃烧",
    "水污染",
    "人群聚集",
    "挖机作业",
    "烟花燃放",
    "垃圾堆放",
    "公园活动",
    "体育活动",
    "占道经营",
    "违章建筑",
    "车辆运输",
    "河道排污",
    "燃烧",
    "庆典集会",
    "操场运动",
    "交通拥堵",
    "违章停车",
    "盗采",
    "秸秆燃烧",
    "河道/湖泊污染",
]

WEATHER_LABELS = ["晴", "雨", "雾", "夜间", "红外", "sunny", "rainy", "night"]

RESTORATION_TYPES = ["雨", "雾", "红外", "低照度", "模糊"]
